version: '3.9'
services:
  redis:
    container_name: redis
    image: 'redis:7.0-rc3'
    ports:
      - '6379:6379'
  database:
    container_name: postgres
    image: 'postgres:14.2-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'D:/data:/var/lib/postgresql/data'
